[params]
  ShowCopyRight = true
  ShowMore = true
  ShowRSS = true
  siteDescription: "Описание сайта по умолчанию"
  truncateSummary: 160  # Максимальная длина description
  plainifySummary: true  # Очистка от HTML-тегов